### ISSUE TITLE
Missing model files

### ISSUE THREAD

**Issue by happydpc** [risenow/GfxCullingMethods#1]
This project is great, but how can I download the test files or generate them. Hope you can offer the test files, that will be very nice. Thanks.

**Comment by risenow** [comment]
You can get it from here https://drive.google.com/drive/folders/17gJjU-XhHQLetuzMHPaSLEklNBG8AX0V?usp=sharing
I will also put this link in the project description(README).

**Comment by risenow** [comment]
The final path to the model folder should look like this: ...\Data\SchoolGirlOBJ
Also you can try to load another OBJ model by changing the path in DemoScene1GenerateFor function(DemoScene1Generate.cpp file), line mesh = SuperMesh::FromFile(device, textureCollection, "Data/SchoolGirlOBJ/D0208059.obj");

**Comment by happydpc** [comment]
Thank you. I will have a test.
